### ISSUE TITLE
Unhandled nil

### ISSUE THREAD

**Issue by xPucTu4** [gmyx/Ultra-Fast-Magnectic-Inserters#1]
When I play with **LuaCombinator 2** and press escape key to close the combinator GUI, the game crashes with this message:
"Error while running event UltraFastMagneticInserterExtra::on_gui_closed (ID 84)"

In /control/commonGUI.lua:42: attempt to index field 'element' (a nil value)
In https://lua-api.factorio.com/latest/events.html#on_gui_closed 'element' is optional.

I changed that line to:
`if event.gui_type == defines.gui_type.custom and event.element ~= nil and event.element.name == self.boxCaption  then`
and it works, however it would be good to be updated on the mods portal, not only for me.

**Comment by gmyx** [comment]
Adding to the next release. Should be this weekend.

Thanks!
